# GitHub Dependabot configuration for tpl-search-extension
# Chrome extension for Toronto Public Library search

version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "adamkwhite"
    assignees:
      - "adamkwhite"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "chrome-extension"
      - "javascript"
    # Group development and testing dependencies
    groups:
      testing-dependencies:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "vitest*"
          - "sinon*"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "eslint*"
          - "typescript*"
          - "vite*"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
    # Security updates always allowed
    allow:
      - dependency-type: "all"
    ignore:
      # Be careful with major TypeScript updates
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]